# Generated by Django 4.2.6 on 2024-01-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('cmanager', models.CharField(max_length=100)),
                ('clocation', models.CharField(max_length=100)),
            ],
        ),
    ]
